### PR TITLE
Apply dynamic measure to small lyrics view

### PR DESCRIPTION
**Pull request by Yuseon-Han**
https://tde.sktelecom.com/pms/browse/AISRVDEV-419?filter=-1

The issue is small lyrics view is not support Text size changing becuase of it's parent has fixed height.
So parent of it become WRAP_CONTENT SIZE. 
And for this,  this PR have change small lyrics view to only have 2 items in their recycler view .

### CODE REVIEW

**Comment by tommy5oo** [comment]
Is the default viewtype SIZE_SMALL?

**Comment by Yuseon-Han** [comment]
> Default is STANDARD

**Comment by tommy5oo** [comment]
> Default is STANDARD

Please check that the size is set correctly in the xml resource.
https://github.com/nugu-developers/nugu-android/blob/master/nugu-ux-kit/src/main/res/layout/view_display_audioplayer_port.xml#L130
https://github.com/nugu-developers/nugu-android/blob/master/nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml#L143
https://github.com/nugu-developers/nugu-android/blob/master/app/src/main/res/layout/custom_media_player.xml#L130

**Comment by Yuseon-Han** [comment]
> > Default is STANDARD
> 
> Please check that the size is set correctly in the xml resource. https://github.com/nugu-developers/nugu-android/blob/master/nugu-ux-kit/src/main/res/layout/view_display_audioplayer_port.xml#L130 https://github.com/nugu-developers/nugu-android/blob/master/nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml#L143 https://github.com/nugu-developers/nugu-android/blob/master/app/src/main/res/layout/custom_media_player.xml#L130

Yes there are correct its small lyrics views

**Review by tommy5oo — APPROVED** [review]

**Review by shshshl09 — APPROVED** [review]

**Pull request merged**
